{% set name = "click" %}
{% set version = "7.0" %}

package:
  name: "energyplus_modelling"
  version: "0.1.0"

source:
  url: https://github.com/codema-dev/energyplus-archetypes

requirements:
  host:
    - pip
    - python
  run:
    - python

test:
  imports:
    - click

about:
  home: https://github.com/codema-dev/energyplus-archetypes
  license: MIT
  license_family: BSD
  summary: Composable command line interface toolkit
